# Even Fibonacci numbers
# Each new term in the Fibonacci sequence is
# generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms 
# will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
# By considering the terms in the Fibonacci 
# sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

# == Solution == #
# An easy way to simplify the problem is to only calculate
# the 2nd, 5th, 8th, 11th, etc. terms since they are the only
# terms that will be even if you start with 1 and 2.
# 3Fi + 2Fi-1 is the next even number after an even number

sequence = [1, 2]
total = 0
while sequence[1] < 4 * 10**6:
    total += sequence[1]

    sequence = [sequence[0]+2*sequence[1], 2*sequence[0]+3*sequence[1]]

print(f'The sum of even Fibonacci numbers is {total}')
